### ISSUE TITLE
Error in texts[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by locusclassicus** [daranzolin/rperseus#12]
Error while getting perseus texts:

```
plato <- perseus_catalog %>% 
filter(group_name == "Plato", language == "eng") %>% 
pull(urn) %>%  map_df(get_perseus_text)
```
Returns

No encoding supplied: defaulting to UTF-8.
Error in texts[[1]] : subscript out of bounds

I have been using this package for quite a while now, everything was ok.

**Comment by daranzolin** [comment]
Hmmm, the response code being returned by server (which I should print to the user) is '502', which isn't something I can fix. 500 level errors usually indicate a problem on their end, not ours. I'll try and learn why and get back to you. Apologies!

**Comment by daranzolin** [comment]
@locusclassicus the server appears to be back up and running and I was able to run your code.

**Comment by locusclassicus** [comment]
This is really cool, since I have already recommended this package to my students. What an awesome thing you did, thank you!

**Comment by daranzolin** [comment]
Thank you for sharing! This is my last remaining connection to classical literature and the digital humanities, so I'm thrilled to hear about its use.
